// Code generated by hertz generator.

package Service

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pusherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepusherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepusherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_llcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _category0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pusher0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpusherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_llpushersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _todoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtodosby_udioMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtodosbynlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _todo0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_lltodosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpusherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallpushersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtodosbyaudioMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getalltodosMw() []app.HandlerFunc {
	// your code...
	return nil
}
