// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	api "github.com/x-start-up/Life-Copilot-Server/biz/router/api"
	service "github.com/x-start-up/Life-Copilot-Server/biz/router/service"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	service.Register(r)

	api.Register(r)
}
